name: Deploy

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /opt/books-portal
          
          # Получаем последние изменения
          git pull
          
          # Обновляем переменные окружения
          source .env
          
          # Обновляем образы
          docker compose pull
          
          # Применяем миграции
          docker compose run --rm app alembic upgrade head
          
          # Перезапускаем сервисы
          docker compose up -d
          
          # Очищаем неиспользуемые образы
          docker image prune -f 